shamefullyHoist: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.24
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  oxlint: '1.68.0'
minimumReleaseAgeExclude:
  - '@soybeanjs/oxc-config@0.2.3'
  - hono@4.12.24
allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
